<?php
/**
 * @var \CustomModule\QuickBuy\Block\Button $block
 * @var \Magento\Framework\Escaper $escaper
 */
$product = $block->getProduct();
?>
<?php if ($product): ?>
    <button type="button" class="action primary tocart" id="quick-buy-button" data-sku="<?php echo $escaper->escapeHtml($product->getSku()) ?>">
        <?php echo __('Buy in 1 click') ?>
    </button>
    <div id="quick-buy-form" class="quick-buy-form" style="display:none;">
        <input type="text" id="phone-number" class="phone-number" placeholder="Enter a phone number" />
        <button type="button" id="submit-phone-number" class="submit-phone-number">Send</button>
    </div>
<?php else: ?>
    <p><?php echo __('Product not found'); ?></p>
<?php endif; ?>


